// @ts-check

/**
 * 侧边栏配置。
 * 这里使用自动生成模式：docs 目录下的文件结构会自动变成侧边栏。
 * 也可以手动定义，详见 https://docusaurus.io/docs/sidebar
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
