// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 通用侧边栏（快速开始等）
  mainSidebar: [
    'intro',
  ],
  // 回声宇宙
  echoverseSidebar: [{type: 'autogenerated', dirName: 'echoverse'}],
  // 黎明之前
  dawnbeforeSidebar: [{type: 'autogenerated', dirName: 'dawnbefore'}],
};

export default sidebars;
